### ISSUE TITLE
Is the a typo in bunceTime

### ISSUE THREAD

**Issue by stalinkay** [zhhz/gulp-ga#6]
Thank you for this package. I think there is a typo in the example shouldn't bunceTime be bounceTime
.pipe(ga({bunceTime: 15}))

Shouldn't it be?
.pipe(ga({bounceTime: 15}))

**Comment by zhhz** [comment]
@stalinkay Thanks for reporting the typo. Just updated the README, please find the latest v0.0.8

**Comment by zhhz** [comment]
Fixed in v0.0.8

**Comment by stalinkay** [comment]
@zhhz, cool but I don't see v0.0.8. Maybe you forgot to push.

**Comment by zhhz** [comment]
@stalinkay Yeah, you are right, I only updated the npm registry, forgot to push to github. Will do it when I get home today. https://www.npmjs.com/package/gulp-ga

**Comment by stalinkay** [comment]
Cool. Peace.



 <http://stalinkay.com/>	 	
 
 
 
 
 
 
 
 
 
 
Samuel Stalin Kapembe <mailto:stalin@stalinkay.com> •  Imagination Specialist <https://stalinkay.com/>
 
stalinkay.com <https://stalinkay.com/> •  +264 81 148 6483

**Comment by stalinkay** [comment]
Cool. Peace.
